[workspace]
members = ["crates/core", "crates/cli", "crates/gui", "crates/wasm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["share121 <2854631158@qq.com>"]
repository = "https://github.com/share121/fast-down"
readme = "README.md"
exclude = ["/.github", "/docs"]

[workspace.dependencies]
fast-down = { version = "2.0.0", path = "crates/core" }
color-eyre = "0.6.3"
reqwest = { version = "0.12.12", features = [
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "http2",
  "rustls-tls",
  "socks",
  "macos-system-configuration",
], default-features = false }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
