[workspace]
members = ["fast-down", "fast-down-cli"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["share121 <2854631158@qq.com>"]
repository = "https://github.com/share121/fast-down"
readme = "README.md"
exclude = ["/.github"]

[workspace.dependencies]
color-eyre = "0.6.3"
reqwest = { version = "0.12.12", features = [
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "http2",
] }
tokio = { version = "1.44.2", features = ["full"] }

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
