name: build

on:
  push:
    tags:
      - v*

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: |
          bun build --compile --minify --bytecode index.ts --target=bun-linux-x64-baseline --outfile fast-down-linux-x64-baseline
          bun build --compile --minify --bytecode index.ts --target=bun-linux-x64-modern --outfile fast-down-linux-x64-modern
          bun build --compile --minify --bytecode index.ts --target=bun-linux-arm64-modern --outfile fast-down-linux-arm64-modern
          bun build --compile --minify --bytecode index.ts --target=bun-windows-x64-baseline --outfile fast-down-windows-x64-baseline
          bun build --compile --minify --bytecode index.ts --target=bun-windows-x64-modern --outfile fast-down-windows-x64-modern
          bun build --compile --minify --bytecode index.ts --target=bun-darwin-x64-baseline --outfile fast-down-darwin-x64-baseline
          bun build --compile --minify --bytecode index.ts --target=bun-darwin-x64-modern --outfile fast-down-darwin-x64-modern
          bun build --compile --minify --bytecode index.ts --target=bun-darwin-arm64-modern --outfile fast-down-darwin-arm64-modern

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Fast Down ${{ github.ref_name }}
          body: 修复了一些已知问题
          draft: false
          prerelease: false
          files: |
            fast-down-linux-x64-baseline
            fast-down-linux-x64-modern
            fast-down-linux-arm64-modern
            fast-down-windows-x64-baseline.exe
            fast-down-windows-x64-modern.exe
            fast-down-darwin-x64-baseline
            fast-down-darwin-x64-modern
            fast-down-darwin-arm64-modern
