name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Test
        run: bun test
